---
- name: Install PostgreSQL
  apt: name={{ item }} state=installed
  with_items:
    - postgresql-9.3
    - postgresql-contrib-9.3
  notify:
    - restart postgresql

- name: Copy pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf
  notify:
    - restart postgresql

- name: Copy pg_ident.conf
  copy: src=pg_ident.conf dest=/etc/postgresql/9.3/main/pg_ident.conf
  notify:
    - restart postgresql

- name: Copy postgresql.conf
  copy: src=postgresql.conf dest=/etc/postgresql/9.3/main/postgresql.conf
  notify:
    - restart postgresql

- name: Restart Postgres so new settings take effect
  service: name=postgresql state=restarted

- name: ensure database is created
  postgresql_db: name={{dbname}}

- name: ensure user has access to database
  postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- name: ensure user does not have unnecessary privilege
  postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB

