---
- name: Checkout static sites
  git: repo=https://github.com/WebCampZg/{{ item }}.static dest=/home/webcamp/web/{{ item }} update=yes
  with_items: static_sites

- name: Copy over nginx vhost file for static sites
  template: src=year.webcampzg.org_static dest=/etc/nginx/sites-available/{{ item }}.webcampzg.org
  with_items: static_sites

- name: Enable domain vhost file for static sites
  file: src=/etc/nginx/sites-available/{{ item }}.webcampzg.org dest=/etc/nginx/sites-enabled/{{ item }}.webcampzg.org state=link
  with_items: static_sites
  notify:
    - restart nginx

