---

# Playbook for setting up Webcamp server
# Tested on Ubuntu 14.04 LTS

# Tested with: Ansible 1.8.2

- name:
  hosts: all
  user: root
  vars_files:
    - vars/user.yml
  roles:
    - { role: common, tags: ["common", "vagrant"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: postgres, tags: ["postgres", "vagrant"] }
    - { role: web, tags: ["web"] }

