---

# Playbook for setting up Webcamp server
# Tested on Ubuntu 14.04 LTS

# Tested with: Ansible 1.8.2

- name:
  hosts: web
  user: root
  vars_files:
    - vars/defaults.yml
    - vars/{{ 'testing' if testing is defined else 'user' }}.yml
  roles:
    # - { role: common, tags: ["common"] }
    - { role: common, tags: ["common", "vagrant"] }
    - { role: nginx, tags: ["nginx"] }
    - { role: postgres, tags: ["postgres", "vagrant"] }
    - { role: web, tags: ["web"] }

